-- =====================================================
-- SUPABASE RESTORE SCRIPT
-- Generated by ACLEF Planning Backup System
-- =====================================================
-- Source backup: 2025-09-26T10:18:46.911772
-- Target database: backup
-- Generated: 2025-09-26T10:25:28.324719
-- Tables: 3
-- Total rows: 7
-- =====================================================

-- Disable foreign key checks temporarily
SET session_replication_role = replica;


-- =====================================================
-- DROP EXISTING TABLES
-- =====================================================

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS admin_sessions CASCADE;
DROP TABLE IF EXISTS absences_formateurs CASCADE;

-- =====================================================
-- CREATE TABLES
-- =====================================================

-- Table: absences_formateurs
CREATE TABLE absences_formateurs (
    id UUID NOT NULL DEFAULT gen_random_uuid()
    formateur_id UUID
    date_debut DATE NOT NULL
    date_fin DATE NOT NULL
    type TEXT NOT NULL
    statut TEXT DEFAULT ''en_attente'::text'
    motif TEXT
    created_at TIMESTAMP DEFAULT now()
);

-- Table: admin_sessions
CREATE TABLE admin_sessions (
    id UUID NOT NULL DEFAULT gen_random_uuid()
    admin_user_id UUID NOT NULL
    email_admin TEXT NOT NULL
    session_start TIMESTAMPTZ NOT NULL DEFAULT now()
    heartbeat TIMESTAMPTZ NOT NULL DEFAULT now()
    session_token TEXT NOT NULL
    is_active BOOLEAN NOT NULL DEFAULT true
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Table: users
CREATE TABLE users (
    id UUID NOT NULL DEFAULT gen_random_uuid()
    prenom TEXT NOT NULL
    nom TEXT NOT NULL
    role TEXT NOT NULL
    email TEXT
    dispositif TEXT
    initiales TEXT
    date_debut DATE
    date_fin DATE
    archive BOOLEAN DEFAULT false
    created_at TIMESTAMP DEFAULT now()
);

-- =====================================================
-- PRIMARY KEYS
-- =====================================================

ALTER TABLE absences_formateurs ADD PRIMARY KEY (id);
ALTER TABLE admin_sessions ADD PRIMARY KEY (id);
ALTER TABLE users ADD PRIMARY KEY (id);

-- =====================================================
-- INSERT DATA
-- =====================================================

-- Data for table: absences_formateurs (2 rows)
INSERT INTO absences_formateurs (id, formateur_id, date_debut, date_fin, type, statut, motif, created_at) VALUES ('absence-001', 'formateur-1', '2025-09-20', '2025-09-22', 'maladie', 'validé', 'Motif absence 1', '2025-09-15 14:30:00');
INSERT INTO absences_formateurs (id, formateur_id, date_debut, date_fin, type, statut, motif, created_at) VALUES ('absence-002', 'formateur-2', '2025-09-21', '2025-09-23', 'congés', 'validé', 'Motif absence 2', '2025-09-16 14:30:00');

-- Data for table: admin_sessions (2 rows)
INSERT INTO admin_sessions (id, admin_user_id, email_admin, session_start, heartbeat, session_token, is_active, created_at) VALUES ('session-001', 'admin-1', 'admin1@aclef.com', '2025-09-25T10:00:00Z', '2025-09-25T10:30:00Z', 'token_abc123_0', true, '2025-09-25T10:00:00Z');
INSERT INTO admin_sessions (id, admin_user_id, email_admin, session_start, heartbeat, session_token, is_active, created_at) VALUES ('session-002', 'admin-2', 'admin2@aclef.com', '2025-09-26T10:01:00Z', '2025-09-26T10:31:00Z', 'token_abc123_1', false, '2025-09-26T10:01:00Z');

-- Data for table: users (3 rows)
INSERT INTO users (id, prenom, nom, role, email, dispositif, archive, created_at) VALUES ('420ed1cc-def4-48e9-b68b-bf1dfa6518500', 'User1', 'Lastname1', 'apprenant', 'user1@example.com', 'HSP', false, '2025-08-27 13:03:24.095074');
INSERT INTO users (id, prenom, nom, role, email, dispositif, archive, created_at) VALUES ('420ed1cc-def4-48e9-b68b-bf1dfa6518501', 'User2', 'Lastname2', 'formateur', 'user2@example.com', 'HSP', false, '2025-08-28 13:03:24.095074');
INSERT INTO users (id, prenom, nom, role, email, dispositif, archive, created_at) VALUES ('420ed1cc-def4-48e9-b68b-bf1dfa6518502', 'User3', 'Lastname3', 'apprenant', NULL, 'HSP', false, '2025-08-29 13:03:24.095074');

-- Total rows inserted: 7

-- =====================================================
-- FOREIGN KEYS
-- =====================================================

ALTER TABLE admin_sessions ADD CONSTRAINT admin_sessions_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES users(id);

-- =====================================================
-- CHECK CONSTRAINTS
-- =====================================================

ALTER TABLE absences_formateurs ADD CONSTRAINT check_absences_formateurs_type CHECK (type = ANY (ARRAY['maladie'::text, 'congés'::text, 'personnel'::text, 'formation'::text]));
ALTER TABLE absences_formateurs ADD CONSTRAINT check_absences_formateurs_statut CHECK (statut = ANY (ARRAY['en_attente'::text, 'validé'::text, 'refusé'::text]));
ALTER TABLE users ADD CONSTRAINT check_users_role CHECK (role = ANY (ARRAY['admin'::text, 'formateur'::text, 'apprenant'::text, 'salarié'::text]));
ALTER TABLE users ADD CONSTRAINT check_users_dispositif CHECK (dispositif = ANY (ARRAY['HSP'::text, 'OPCO'::text]));

-- =====================================================
-- RE-ENABLE CONSTRAINTS
-- =====================================================

-- Re-enable foreign key checks
SET session_replication_role = DEFAULT;

-- =====================================================
-- RESTORE COMPLETE
-- =====================================================
