name: supabase-backup-cli

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  schedule:
    # Tous les jours à minuit UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PostgreSQL and disable IPv6
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          # Disable IPv6 pour forcer IPv4
          echo 'net.ipv6.conf.all.disable_ipv6 = 1' | sudo tee -a /etc/sysctl.conf
          echo 'net.ipv6.conf.default.disable_ipv6 = 1' | sudo tee -a /etc/sysctl.conf
          sudo sysctl -p

      - name: Create backup directory
        run: mkdir -p supabase-backups

      - name: Check if backup is enabled
        run: |
          if [ "${{ vars.BACKUP_ENABLED }}" != "true" ]; then
            echo "Backup is disabled. Set BACKUP_ENABLED variable to 'true' to enable."
            exit 0
          fi

      - name: Backup database roles
        run: |
          pg_dumpall --roles-only --host=db.mkbchdhbgdynxwfhpxbw.supabase.co --port=5432 --username=postgres > supabase-backups/roles.sql
        env:
          PGPASSWORD: Tours1975&&&&

      - name: Backup database schema
        run: |
          pg_dump --schema-only --host=db.mkbchdhbgdynxwfhpxbw.supabase.co --port=5432 --username=postgres --dbname=postgres > supabase-backups/schema.sql
        env:
          PGPASSWORD: Tours1975&&&&

      - name: Backup database data
        run: |
          pg_dump --data-only --host=db.mkbchdhbgdynxwfhpxbw.supabase.co --port=5432 --username=postgres --dbname=postgres > supabase-backups/data.sql
        env:
          PGPASSWORD: Tours1975&&&&

      - name: Create backup timestamp
        run: |
          echo "Backup created on: $(date)" > supabase-backups/backup-info.txt
          echo "Database URL: ${{ vars.SUPABASE_PROJECT_URL || 'Not specified' }}" >> supabase-backups/backup-info.txt

      - name: Commit backup files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'supabase backup CLI - $(date)'
          file_pattern: 'supabase-backups/*'